### ISSUE TITLE
The station stream function no longer works

### ISSUE THREAD

**Issue by zupermiez** [jonasrmichel/radio-garden-go#1]
Do you know if they have moved it somewhere else, have they purposefully removed it or am i just doing something wrong? Also suggestions for any other ways to do this if that does not work anymore?

in browser
https://radio.garden/api/ara/content/listen/NCzBvLcQ/channel.mp3
{"error":"Not found"}

in cmd
radio-garden station stream -i DfyUx0yR 
Error: received status "Not Found" (expected "Found")

**Comment by jonasrmichel** [comment]
Hi @zupermiez! :wave: 

It doesn't appear that the Radio Garden API has changed -- other stations (channels) I frequent still work.

Perhaps this station was de-listed from the Radio Garden database. Are you able to find and listen to that station via the Radio Garden app or web UI?

**Comment by jonasrmichel** [comment]
Hm, hang on ... `NCzBvLcQ` and `DfyUx0yR` both appear to be *place* identifiers (Chincoteague Island VA and Uelzen, Germany). 

You'll need a *station* identifier for listening. For example, try `V6DXPiZz` (WCTG-FM 96.5 in Chincoteague Island VA) or `MiD7gD0a` (Radio ZUSA in Uelzen, Germany).

In the Radio Garden database, each station is associated with a place. You can provide a place identifier to the `stations` command to retrieve the stations associated with a place.

**Comment by zupermiez** [comment]
big thankyou
